# Generated by Django 3.0.2 on 2020-01-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200109_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='belongsToCat',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('K', 'KIDS')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
