# Generated by Django 3.0.2 on 2020-01-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200113_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('B', 'Boy'), ('G', 'Girl'), ('Sh', 'Shoes'), ('J', 'Jacket'), ('Je', 'Jeans'), ('H', 'Hoodies'), ('A', 'Accesories')], max_length=20, null=True),
        ),
    ]
