# Generated by Django 3.0.2 on 2020-01-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200113_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='Item Description'),
        ),
    ]
