# Generated by Django 3.0.2 on 2020-01-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200114_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
