# Generated by Django 3.0.2 on 2020-01-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_item_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='views',
            field=models.IntegerField(default='0'),
        ),
    ]
