# Generated by Django 3.0.2 on 2020-01-17 13:33

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_item_shipping_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shipping_country',
        ),
        migrations.CreateModel(
            name='shipping_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_country', django_countries.fields.CountryField(default='Morocco', max_length=2)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_country', to='register.Item')),
            ],
        ),
    ]
