# Generated by Django 3.0.2 on 2020-01-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_item_countries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shipping_item',
        ),
    ]
